FROM openjdk:8u292
LABEL maintainer="hey@bpaulino.com"

ARG SBT_VERSION=1.5.5

# Install sbt
RUN \
  apt-get install -y apt-transport-https && \
  echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list && \
  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 && \
  apt-get update && \
  apt-get install sbt -y && \
  sbt sbtVersion
