name: Docker Build

on:
  push:
    branches:
      - master
  # Enable "run workflow" button on Github UI
  # See: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: Build Base Image
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: docker login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: docker build
        run: |
          docker buildx build --file Dockerfile.base --platform linux/arm64,linux/amd64 -t brunojppb/base-sbt:latest --push
